#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__) + '/../game')

require 'ugly_trivia_game'

not_a_winner = false

game = UglyTrivia::Game.new

game.add 'Chet'
#game.add 'Pat'
#game.add 'Sue'

begin
  
  game.roll(rand(5) + 1)
  
  if rand(9) == 7
    not_a_winner = game.wrong_answer
  else
    not_a_winner = game.correct_answer_and_not_done?
  end
  
  
  
end while not_a_winner
